"""Add created_at column to files table

Revision ID: 06cdc0c24d9d
Revises: 6e3d7fd92f07
Create Date: 2025-07-20 04:53:55.808060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cdc0c24d9d'
down_revision: Union[str, Sequence[str], None] = '6e3d7fd92f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'created_at')
    # ### end Alembic commands ###
